In [14]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv('vendas_tech.csv', encoding='utf-8')
display(df_vendas.head())

df_gerentes = pd.read_excel('gerentes_lojas.xlsx')
display(df_gerentes)

C:\Users\XXX\AppData\Local\Temp\ipykernel_3412\1324735687.py:4: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vendas = pd.read_csv('vendas_tech.csv', encoding='utf-8')

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000